# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AponoCli < Formula
  desc "View, request and receive permissions to services, DBs and applications."
  homepage "https://www.apono.io"
  version "1.3.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/apono-io/apono-cli/releases/download/v1.3.3/apono-cli_1.3.3_darwin_arm64.tar.gz"
      sha256 "8405f946231dee8e3476be48920877b8ee54d1bf89a19a150650bdc930eff6e7"

      def install
        bin.install "apono" => "apono"
        man1.install Dir["contrib/manpage/apono*.1"]
        bash_completion.install "contrib/completion/bash/apono"
        zsh_completion.install "contrib/completion/zsh/_apono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/apono-io/apono-cli/releases/download/v1.3.3/apono-cli_1.3.3_darwin_amd64.tar.gz"
      sha256 "ca4882d3a7e274cc6bba1e643015237ae0ca6dcd70fcd05a39d3ef74c4b4a2c6"

      def install
        bin.install "apono" => "apono"
        man1.install Dir["contrib/manpage/apono*.1"]
        bash_completion.install "contrib/completion/bash/apono"
        zsh_completion.install "contrib/completion/zsh/_apono"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/apono-io/apono-cli/releases/download/v1.3.3/apono-cli_1.3.3_linux_armv6.tar.gz"
      sha256 "b6174ed29bc5b729143405cccbb30267ea5029bf5795fc020eb5ef02e0179ba4"

      def install
        bin.install "apono" => "apono"
        man1.install Dir["contrib/manpage/apono*.1"]
        bash_completion.install "contrib/completion/bash/apono"
        zsh_completion.install "contrib/completion/zsh/_apono"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/apono-io/apono-cli/releases/download/v1.3.3/apono-cli_1.3.3_linux_arm64.tar.gz"
      sha256 "1b88c99dbd2026db7fcfab4e90634914ce0c2b66c9641152924fb345105c2ab3"

      def install
        bin.install "apono" => "apono"
        man1.install Dir["contrib/manpage/apono*.1"]
        bash_completion.install "contrib/completion/bash/apono"
        zsh_completion.install "contrib/completion/zsh/_apono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/apono-io/apono-cli/releases/download/v1.3.3/apono-cli_1.3.3_linux_amd64.tar.gz"
      sha256 "81ab69542070a611711397d53151cd3ef4f08dba69f4c9eb1da848a08e65cd8b"

      def install
        bin.install "apono" => "apono"
        man1.install Dir["contrib/manpage/apono*.1"]
        bash_completion.install "contrib/completion/bash/apono"
        zsh_completion.install "contrib/completion/zsh/_apono"
      end
    end
  end

  test do
    system "#{bin}/apono version"
  end
end
