# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AponoCli < Formula
  desc "View, request and receive permissions to services, DBs and applications."
  homepage "https://www.apono.io"
  version "1.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/apono-io/apono-cli/releases/download/v1.3.1/apono-cli_1.3.1_darwin_arm64.tar.gz"
      sha256 "50770fd8ac22a2c6e754ba52cd434067530d9e934d6ba75a13d7180ac40e4cbf"

      def install
        bin.install "apono" => "apono"
        man1.install Dir["contrib/manpage/apono*.1"]
        bash_completion.install "contrib/completion/bash/apono"
        zsh_completion.install "contrib/completion/zsh/_apono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/apono-io/apono-cli/releases/download/v1.3.1/apono-cli_1.3.1_darwin_amd64.tar.gz"
      sha256 "b8ca211f5c2ce90518914cbf5e0b4d9cdb9983ee052f001c05a5054d23b6fa93"

      def install
        bin.install "apono" => "apono"
        man1.install Dir["contrib/manpage/apono*.1"]
        bash_completion.install "contrib/completion/bash/apono"
        zsh_completion.install "contrib/completion/zsh/_apono"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/apono-io/apono-cli/releases/download/v1.3.1/apono-cli_1.3.1_linux_armv6.tar.gz"
      sha256 "67154ff1a80ae31cdc6ff3c613d2d2d55a84f42d9f1458f4bee4c61cbb23d069"

      def install
        bin.install "apono" => "apono"
        man1.install Dir["contrib/manpage/apono*.1"]
        bash_completion.install "contrib/completion/bash/apono"
        zsh_completion.install "contrib/completion/zsh/_apono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/apono-io/apono-cli/releases/download/v1.3.1/apono-cli_1.3.1_linux_amd64.tar.gz"
      sha256 "83ce642097be231235ea9ff56ff5f2142dc2b3450119c4db6dae1b8bd051e938"

      def install
        bin.install "apono" => "apono"
        man1.install Dir["contrib/manpage/apono*.1"]
        bash_completion.install "contrib/completion/bash/apono"
        zsh_completion.install "contrib/completion/zsh/_apono"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/apono-io/apono-cli/releases/download/v1.3.1/apono-cli_1.3.1_linux_arm64.tar.gz"
      sha256 "53cf3ffaadd6a68861a77584b0c07bf977222602a932987b0bf3eae26291060c"

      def install
        bin.install "apono" => "apono"
        man1.install Dir["contrib/manpage/apono*.1"]
        bash_completion.install "contrib/completion/bash/apono"
        zsh_completion.install "contrib/completion/zsh/_apono"
      end
    end
  end

  test do
    system "#{bin}/apono version"
  end
end
